// <auto-generated />
using System;
using DelEdAllotment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DelEdAllotment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031125828_seat-allotment")]
    partial class seatallotment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DelEdAllotment.Models.Centres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CentreCode")
                        .HasColumnType("int");

                    b.Property<string>("CentreName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_unicode_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CentreName"), "utf8mb4");

                    b.Property<string>("CentreNameHindi")
                        .HasColumnType("longtext");

                    b.Property<string>("CentreTableSession")
                        .HasColumnType("longtext");

                    b.Property<int>("CityCode")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .UseCollation("utf8mb4_unicode_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CityName"), "utf8mb4");

                    b.Property<string>("CityNameHindi")
                        .HasColumnType("longtext");

                    b.Property<int?>("IncreasedCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("utilisedSeat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Centre");
                });

            modelBuilder.Entity("DelEdAllotment.Models.Registrations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("AssignedCentre")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedCity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Centre2")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FName")
                        .HasColumnType("longtext");

                    b.Property<int?>("FeeAmount")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Graduation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HomeDistrict")
                        .HasColumnType("longtext");

                    b.Property<string>("HusbandName")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("MName")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ph")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhType")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PreferredCityCode")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationNo")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RollNumber")
                        .HasColumnType("int");

                    b.Property<int?>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("Scribe")
                        .HasColumnType("longtext");

                    b.Property<string>("Session")
                        .HasColumnType("longtext");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("longtext");

                    b.Property<string>("SubCategory")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("University")
                        .HasColumnType("longtext");

                    b.Property<string>("Warg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("DelEdAllotment.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CentreCode")
                        .HasColumnType("longtext");

                    b.Property<int?>("CityCode")
                        .HasColumnType("int");

                    b.Property<int?>("RoomCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("RoomNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
